version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Projects/Proj1/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
#    - location: scripts/start_server
#      timeout: 300
#  ApplicationStop:
#    - location: scripts/stop_server
#      timeout: 300

